### ISSUE TITLE
Health Manager not needed with Diego

### ISSUE THREAD

**Issue by gtantachuco-pivotal** [pivotalservices/shekel#2]
Hey guys,
Nice work keeping Shekel up-to-date. Just noticed something really minor. The 1.6 estimate includes 1 Health Manager, which is no longer needed when using Diego per: http://docs.pivotal.io/pivotalcf/opsguide/diego-overview.html
Here is an excerpt: "In the PCF 1.6 release, Diego replaces the DEAs and the Health Manager. Diego is installed and enabled in PCF 1.6 by default."

**Comment by virtmerlin** [comment]
Thats an old build "what u asked for". We fixed in a newer build

On Friday, January 8, 2016, Guillermo Tantachuco <notifications@github.com>
wrote:

> Hey guys,
> Nice work keeping Shekel up-to-date. Just noticed something really minor.
> The 1.6 estimate includes 1 Health Manager, which is no longer needed when
> using Diego per:
> http://docs.pivotal.io/pivotalcf/opsguide/diego-overview.html
> Here is an excerpt: "In the PCF 1.6 release, Diego replaces the DEAs and
> the Health Manager. Diego is installed and enabled in PCF 1.6 by default."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotalservices/shekel/issues/2>.
>


-- 
Merlin Glynn
mglynn@pivotal.io
001-214-551-8074

**Comment by gtantachuco-pivotal** [comment]
The latest build at: https://pcfsizer.cfapps.pez.pivotal.io shows 3 Health Managers:

<img width="833" alt="screen shot 2016-01-08 at 5 25 07 pm" src="https://cloud.githubusercontent.com/assets/612601/12212170/e36639a8-b62c-11e5-8e8f-ee5b3d0f650c.png">

**Comment by krujos** [comment]
Thanks for letting us know. Would you mind submitting a pr
(/is/data/ers*.json has the file, should be pretty self explanatory. In our
and about or id just do it.

**Comment by rjain-pivotal** [comment]
Committed the change.
